---
version: "3.8"
services:
  movies:
    image: ganeshlalam163/moviesrepo:latest
    ports:
      - 81:80
    deploy:
      replicas: 3
    
  train:
    image: ganeshlalam163/trainrepo:latest
    ports:
      - 82:80
    deploy:
      replicas: 3
    
  dth:
    image: ganeshlalam163/dthrepo:latest
    ports:
      - 83:80
    deploy:
      replicas: 3
   
  recharge:
    image: ganeshlalam163/rechargerepo:latest
    ports:
      - 84:80
    deploy:
      replicas: 3
    

